INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Capitao America: O Primeiro Vingador', 'https://www.themoviedb.org/t/p/original/yFuKvT4Vm3sKHdFY4eG6I4ldAnn.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Capita Marvel', 'https://www.themoviedb.org/t/p/original/nBS1vONGYrsL2C68C2oDQ3eKJR1.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Homem de Ferro', 'https://www.themoviedb.org/t/p/original/cdsjxSR55VS80IiJfrQ9i9pWqrp.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Incrivel Hulk', 'https://www.themoviedb.org/t/p/original/jPu8yiadqgzwFPGKJmGo637ASVP.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Homem de Ferro 2', 'https://www.themoviedb.org/t/p/original/7lmBufEG7P7Y1HClYK3gCxYrkgS.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Thor', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cDJ61O1STtbWNBwefuqVrRe3d7l.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Os Vingadores', 'https://www.themoviedb.org/t/p/original/nNmJRkg8wWnRmzQDe2FwKbPIsJV.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Loki', 'https://www.themoviedb.org/t/p/original/anp5ubvD7frvXMZMaMuxeFRhfWm.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'What If...?', 'https://www.themoviedb.org/t/p/original/4N6zEMfZ57zNEQcM8gWeERFupMv.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Homem de Ferro 3', 'https://www.themoviedb.org/t/p/original/iVped1djsF0tvGkvnHbzsE3ZPTF.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Thor: O Mundo Sombrio', 'https://www.themoviedb.org/t/p/original/uhYoytlNaq46dG81wLmHqaSuzWu.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Capitao America 2: O Soldado Invernal', 'https://www.themoviedb.org/t/p/original/55zqM1Dt1kVFOQf0ddgjhS3SCf7.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Guardioes da Galaxia', 'https://www.themoviedb.org/t/p/original/2UFxrUHVuSK3Tth7DvQQlF4mGTd.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Guardioes da Galaxia - Vol. 2', 'https://www.themoviedb.org/t/p/original/aJn9XeesqsrSLKcHfHP4u5985hn.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Demolidor', 'https://www.themoviedb.org/t/p/original/gLACGQiS8kRP2hDnzdmIYo2uRRc.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Vingadores: Era de Ultron', 'https://www.themoviedb.org/t/p/original/wjklF1KOHUcKezUjjyAnG5Hi6bK.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Homem-Formiga', 'https://www.themoviedb.org/t/p/original/1K3JmSNUN8OpjYsCjc0Hy0SYxAb.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Capitao America: Guerra Civil', 'https://www.themoviedb.org/t/p/original/wdwcOBMkt3zmPQuEMxB3FUtMio2.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Viuva Negra', 'https://www.themoviedb.org/t/p/original/keIxh0wPr2Ymj0Btjh4gW7JJ89e.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Pantera Negra', 'https://www.themoviedb.org/t/p/original/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Homem-Aranha: De Volta ao Lar', 'https://www.themoviedb.org/t/p/original/b5EhDAly33c6Allclns7u22hHUb.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Doutor Estranho', 'https://www.themoviedb.org/t/p/original/qUv51IFUvVRAP2379ThmA3eLJx6.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Thor: Ragnarok', 'https://www.themoviedb.org/t/p/original/6G2fLCVm9fiLyHvBrccq6GSe2ih.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Homem-Formiga e a Vespa', 'https://www.themoviedb.org/t/p/original/iYdgEUE2W2aJkgqfSjf1x3gFfuV.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Vingadores: Guerra Infinita', 'https://www.themoviedb.org/t/p/original/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Vingadores: Ultimato', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Thor: Amor e Trovao', 'https://www.themoviedb.org/t/p/original/jsoz1HlxczSuTx0mDl2h0lxy36l.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'WandaVision', 'https://www.themoviedb.org/t/p/original/33j33midGw49BBxiqlNZeZ6PZ0O.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Falcao e o Soldado Invernal', 'https://www.themoviedb.org/t/p/original/aTjbqMONy77fHJrIYu14g1F0d5h.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Shang-Chi e a Lenda dos Dez Anéis', 'https://www.themoviedb.org/t/p/original/cinER0ESG0eJ49kXlExM0MEWGxW.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Homem-Aranha: Longe de Casa', 'https://www.themoviedb.org/t/p/original/ng6SSB3JhbcpKTwbPDsRwUYK8Cq.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Homem-Aranha: Sem Volta Para Casa', 'https://www.themoviedb.org/t/p/original/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Eternos', 'https://www.themoviedb.org/t/p/original/k2twTjSddgLc1oFFHVibfxp2kQV.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Pantera Negra: Wakanda para Sempre', 'https://www.themoviedb.org/t/p/original/fSfWloWi5rmqbmC7GhO0HY2TMZW.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Doutor Estranho no Multiverso da Loucura', 'https://www.themoviedb.org/t/p/original/gUNRlH66yNDH3NQblYMIwgZXJ2u.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Gaviao Arqueiro', 'https://www.themoviedb.org/t/p/original/1R68vl3d5s86JsS2NPjl8UoMqIS.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Cavaleiro da Lua', 'https://www.themoviedb.org/t/p/original/vfWdZYGR5505zrCdgTHteFyARu3.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Pantera Negra: Wakanda para Sempre', 'https://www.themoviedb.org/t/p/original/fSfWloWi5rmqbmC7GhO0HY2TMZW.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Guardioes da Galaxia - Vol. 3', 'https://www.themoviedb.org/t/p/original/ewmbxsDBhAN0AJR0FUPWjJx2QY.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Homem-Aranha', 'https://www.themoviedb.org/t/p/original/uIrA2NGv0H1VhsdTyOui5WC6piM.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Homem-Aranha 2', 'https://www.themoviedb.org/t/p/original/dtJybnuZCfPt96OaqbVD7K6yt1W.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Homem-Aranha 3', 'https://www.themoviedb.org/t/p/original/6MQmtWk4cFwSDyNvIgoJRBIHUT3.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Espetacular Homem-Aranha', 'https://www.themoviedb.org/t/p/original/d2J9TL7r639S2jddfymeSEwXgmN.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Espetacular Homem-Aranha 2', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/u7SeO6Y42P7VCTWLhpnL96cyOqd.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'The Witcher', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/jBJWaqoSCiARWtfV0GlqHrcdidd.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Matrix Resurrections', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/hv7o3VgfsairBoQFAawgaQ4cR1m.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Projeto X', 'https://www.themoviedb.org/t/p/original/5vAv4h4vugleYsbsNkUb9kcrk8h.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Venom', 'https://www.themoviedb.org/t/p/original/VuukZLgaCrho2Ar8Scl9HtV3yD.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Venom: Tempo de Carnificina', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Finalmente 18', 'https://www.themoviedb.org/t/p/original/bGePh6CyZIzrueokpvyijWeBZ4X.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Breaking Bad', 'https://www.themoviedb.org/t/p/original/bsNm9z2TJfe0WO3RedPGWQ8mG1X.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Game of Thrones', 'https://www.themoviedb.org/t/p/original/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Stranger Things', 'https://www.themoviedb.org/t/p/original/x93QzAgtHeRGgfK51Jh6URClBG8.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Peaky Blinders', 'https://www.themoviedb.org/t/p/original/kfUWupX3phYp7AleZA2U1dmVcjX.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'How I Met Your Mother', 'https://www.themoviedb.org/t/p/original/gvEisYtZ0iBMjnO3zqFU2oM26oM.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'The Boys', 'https://www.themoviedb.org/t/p/original/mGVrXeIjyecj6TKmwPVpHlscEmw.jpg');



